### ISSUE TITLE
Any interest in setting up a Discord Server to track and share operational topics related to running FISSURE?

### ISSUE THREAD

**Issue by rabarar** [ainfosec/FISSURE#25]
would be great to establish community interaction using discord and share experiences and insights from using FISSURE - I can set up a server if wanted - or glad to join if someone else does! :)

**Comment by cpoore1** [comment]
I’ll set one up today and add links to it in the README.

**Comment by rabarar** [comment]
Excellent

**Comment by cpoore1** [comment]
https://discord.gg/JZDs5sgxcG

Will update the README in the next commit.
